name: CI v2

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.16']
    steps:
    - name: Setup
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Prerequisites
      run: |
        sudo apt-get update
        sudo apt-get -y install libvlc-dev vlc-plugin-base vlc-plugin-video-output vlc-plugin-access-extra

    - name: Checkout
      uses: actions/checkout@v3

    - name: Dependencies
      working-directory: ./v2
      run: |
        go version
        go get -v -t -d ./...
        go install golang.org/x/lint/golint@latest

    - name: Lint
      working-directory: ./v2
      run: golint -set_exit_status=1 ./...

    - name: Vet
      working-directory: ./v2
      run: go vet -unsafeptr=false ./...

    - name: Test
      working-directory: ./v2
      run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Coverage
      uses: codecov/codecov-action@v2.1.0
